#!/usr/bin/env bash
#
# Builds the JNI shim for one platform and stages it, the pinned libchdb and their metadata
# into that platform's Maven module, ready for `mvn package`.
#
# Produces the layout from work plan section 4.2:
#
#   chdb-native-<platform>/target/native/
#     META-INF/chdb/native/<os>/<arch>/libchdb.so
#     META-INF/chdb/native/<os>/<arch>/libchdb_java_jni.{so,dylib}
#     META-INF/chdb/native/<os>/<arch>/manifest.properties
#     META-INF/chdb/native/<os>/<arch>/sha256sums.txt
#     META-INF/licenses/
#     META-INF/sbom/
#
# Usage:
#   scripts/build-native.sh <platform-id> [--local-engine <path/to/libchdb.so>]
#
# platform-id: macos-aarch64 macos-x86_64 linux-x86_64-gnu linux-aarch64-gnu
#
# Cross-compiling is not attempted: each platform package is built on its own platform in CI.
# The script refuses a platform id that does not match the machine it is running on, because a
# shim linked against the wrong architecture fails at System.load() in a user's JVM rather than
# here.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PROPS="${SCRIPT_DIR}/engine.properties"

die() { printf 'build-native: %s\n' "$*" >&2; exit 1; }

prop() {
  local key="$1" value
  value="$(sed -n "s/^${key}=//p" "$PROPS" | head -n1)"
  [ -n "$value" ] || die "no '${key}' in ${PROPS}"
  printf '%s' "$value"
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

PLATFORM="${1:-}"
[ -n "$PLATFORM" ] || die "usage: $0 <platform-id> [--local-engine <path>]"
shift

LOCAL_ENGINE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --local-engine)
      LOCAL_ENGINE="${2:-}"
      [ -n "$LOCAL_ENGINE" ] || die "--local-engine needs a path"
      shift 2
      ;;
    *) die "unknown argument: $1" ;;
  esac
done

# ---------------------------------------------------------------- platform sanity

case "$(uname -s)" in
  Darwin) HOST_OS=macos ;;
  Linux)  HOST_OS=linux ;;
  *)      die "unsupported host OS $(uname -s); V1 builds on Linux and macOS only" ;;
esac
case "$(uname -m)" in
  arm64|aarch64) HOST_ARCH=aarch64 ;;
  x86_64|amd64)  HOST_ARCH=x86_64 ;;
  *)             die "unsupported host CPU $(uname -m)" ;;
esac

case "$PLATFORM" in
  macos-aarch64)     OS=macos; ARCH=aarch64; MODULE=chdb-native-macos-aarch64 ;;
  macos-x86_64)      OS=macos; ARCH=x86_64;  MODULE=chdb-native-macos-x86_64 ;;
  linux-x86_64-gnu)  OS=linux; ARCH=x86_64;  MODULE=chdb-native-linux-x86_64-gnu ;;
  linux-aarch64-gnu) OS=linux; ARCH=aarch64; MODULE=chdb-native-linux-aarch64-gnu ;;
  *) die "unknown platform '${PLATFORM}'" ;;
esac

if [ "$OS" != "$HOST_OS" ] || [ "$ARCH" != "$HOST_ARCH" ]; then
  die "refusing to build ${PLATFORM} on ${HOST_OS}-${HOST_ARCH}.
Each platform package is built on its own platform: a shim linked for another architecture
fails at System.load() in a user's JVM rather than here. Run this on a ${PLATFORM} machine."
fi

ENGINE_VERSION="$(prop engine.version)"
LIBNAME="$(prop "libname.${PLATFORM}")"
JNINAME="$(prop "jniname.${PLATFORM}")"

# ---------------------------------------------------------------- engine

ENGINE_DIR="${ROOT}/target/engine/${PLATFORM}"
if [ -n "$LOCAL_ENGINE" ]; then
  bash "${SCRIPT_DIR}/fetch-libchdb.sh" --local "$PLATFORM" "$LOCAL_ENGINE" "$ENGINE_DIR"
else
  bash "${SCRIPT_DIR}/fetch-libchdb.sh" "$PLATFORM" "$ENGINE_DIR"
fi
[ -f "${ENGINE_DIR}/${LIBNAME}" ] || die "no ${LIBNAME} in ${ENGINE_DIR}"

# ---------------------------------------------------------------- JNI headers

# javac -h output. Generated by `mvn -pl chdb-jdbc compile`; including it makes a Java/native
# signature mismatch a compile error rather than a runtime UnsatisfiedLinkError.
HEADER_DIR="${ROOT}/chdb-jdbc/target/native-headers"
if [ ! -f "${HEADER_DIR}/org_chdb_internal_ChdbNative.h" ]; then
  die "no generated JNI header in ${HEADER_DIR}.
Run 'mvn -pl chdb-jdbc compile' first: the shim compiles against javac -h output so that a
signature drift between Java and native is caught at build time."
fi

# ---------------------------------------------------------------- shim

BUILD_DIR="${ROOT}/target/jni-build-${PLATFORM}"
cmake -S "${ROOT}/chdb-jni" -B "$BUILD_DIR" \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCHDB_ENGINE_DIR="$ENGINE_DIR" \
  -DCHDB_ENGINE_VERSION="$ENGINE_VERSION" \
  -DCHDB_JNI_HEADER_DIR="$HEADER_DIR"
cmake --build "$BUILD_DIR" --parallel

SHIM="${BUILD_DIR}/${JNINAME}"
[ -f "$SHIM" ] || die "cmake did not produce ${SHIM}"

# ---------------------------------------------------------------- dynamic-linkage checks
#
# Work plan section 5.3: the shim must find libchdb next to itself and must not carry any
# absolute path from this build machine. Both are checked here rather than discovered by a
# user whose JVM cannot load the package.

printf 'build-native: checking dynamic linkage of %s\n' "$JNINAME"
if [ "$OS" = macos ]; then
  DEPS="$(otool -L "$SHIM" | tail -n +2)"
  RPATHS="$(otool -l "$SHIM" | awk '/LC_RPATH/{found=1} found && /path /{print $2; found=0}')"
  printf '%s\n' "$RPATHS" | grep -qx '@loader_path' \
    || die "shim has no @loader_path LC_RPATH; it will not find ${LIBNAME} beside itself.
Found: ${RPATHS}"
  printf '%s\n' "$DEPS" | grep -q "@rpath/${LIBNAME}" \
    || die "shim does not reference @rpath/${LIBNAME}. Found:
${DEPS}"
else
  DEPS="$(objdump -p "$SHIM" | grep NEEDED || true)"
  RUNPATH="$(objdump -p "$SHIM" | awk '/RUNPATH|RPATH/{print $2}')"
  printf '%s\n' "$RUNPATH" | grep -q '\$ORIGIN' \
    || die "shim has no \$ORIGIN RUNPATH; it will not find ${LIBNAME} beside itself.
Found: ${RUNPATH}"
  printf '%s\n' "$DEPS" | grep -q "$LIBNAME" \
    || die "shim does not link ${LIBNAME}. Found:
${DEPS}"
fi

# A load command naming a build-machine directory is a package that works only on the machine
# that built it -- the failure mode this check exists to make impossible.
if printf '%s\n' "$DEPS" | grep -Eq '(^|[[:space:]])(/Users/|/home/|/build/|/workspace/|/__w/)'; then
  die "shim references an absolute build-machine path:
$(printf '%s\n' "$DEPS" | grep -E '(/Users/|/home/|/build/|/workspace/|/__w/)')"
fi

# ---------------------------------------------------------------- staging

STAGE="${ROOT}/${MODULE}/target/native"
NATIVE_DIR="${STAGE}/META-INF/chdb/native/${OS}/${ARCH}"
rm -rf "$STAGE"
mkdir -p "$NATIVE_DIR" "${STAGE}/META-INF/licenses" "${STAGE}/META-INF/sbom"

install -m 0755 "${ENGINE_DIR}/${LIBNAME}" "${NATIVE_DIR}/${LIBNAME}"
install -m 0755 "$SHIM" "${NATIVE_DIR}/${JNINAME}"

# Debug symbols stay out of the runtime JAR and are archived separately by CI: they are several
# times the size of the library itself (1.5 GB unpacked for the engine).
if [ -d "${SHIM}.dSYM" ]; then
  rm -rf "${ROOT}/target/debug-symbols/${PLATFORM}"
  mkdir -p "${ROOT}/target/debug-symbols/${PLATFORM}"
  cp -R "${SHIM}.dSYM" "${ROOT}/target/debug-symbols/${PLATFORM}/"
  printf 'build-native: debug symbols archived to target/debug-symbols/%s (not in the JAR)\n' "$PLATFORM"
fi
if [ "$OS" = linux ]; then
  if command -v objcopy >/dev/null 2>&1; then
    mkdir -p "${ROOT}/target/debug-symbols/${PLATFORM}"
    objcopy --only-keep-debug "${NATIVE_DIR}/${JNINAME}" \
      "${ROOT}/target/debug-symbols/${PLATFORM}/${JNINAME}.debug"
    objcopy --strip-debug "${NATIVE_DIR}/${JNINAME}"
    printf 'build-native: debug symbols split to target/debug-symbols/%s\n' "$PLATFORM"
  fi
fi

GIT_COMMIT="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || printf 'unknown')"
BINDING_REVISION="$(sed -n 's:.*<chdb.binding.revision>\(.*\)</chdb.binding.revision>.*:\1:p' "${ROOT}/pom.xml" | head -n1)"
JNI_ABI="$(sed -n 's:.*<chdb.jni.abi.version>\(.*\)</chdb.jni.abi.version>.*:\1:p' "${ROOT}/pom.xml" | head -n1)"
JAVA_API="$(sed -n 's:.*<chdb.java.api.version>\(.*\)</chdb.java.api.version>.*:\1:p' "${ROOT}/pom.xml" | head -n1)"
ENGINE_SOURCE="$(sed -n 's/^engine.source=//p' "${ENGINE_DIR}/engine.source" | head -n1)"

ENGINE_SHA="$(sha256_of "${NATIVE_DIR}/${LIBNAME}")"
JNI_SHA="$(sha256_of "${NATIVE_DIR}/${JNINAME}")"

# Recorded as separate fields rather than as a version string to be split apart: the loader
# compares engine.version, jni.abi.version and java.api.version independently (work plan
# section 4.3).
cat > "${NATIVE_DIR}/manifest.properties" <<EOF
# Generated by scripts/build-native.sh -- do not edit.
engine.version=${ENGINE_VERSION}
engine.source=${ENGINE_SOURCE}
engine.library=${LIBNAME}
engine.library.sha256=${ENGINE_SHA}
jni.library=${JNINAME}
jni.library.sha256=${JNI_SHA}
jni.abi.version=${JNI_ABI}
java.api.version=${JAVA_API}
binding.revision=${BINDING_REVISION}
platform.id=${PLATFORM}
platform.os=${OS}
platform.arch=${ARCH}
platform.libc=$([ "$OS" = linux ] && printf 'gnu' || printf 'system')
build.commit=${GIT_COMMIT}
build.host.os=$(uname -s)
build.host.release=$(uname -r)
build.toolchain=$(cc --version 2>/dev/null | head -n1 || printf 'unknown')
build.cmake=$(cmake --version | head -n1)
EOF

# sha256sum(1) format, so the file can be verified with the standard tool as well as by the
# Java loader.
( cd "$NATIVE_DIR" && printf '%s  %s\n' "$ENGINE_SHA" "$LIBNAME" > sha256sums.txt \
  && printf '%s  %s\n' "$JNI_SHA" "$JNINAME" >> sha256sums.txt )

# ---------------------------------------------------------------- licences and SBOM

cp "${ROOT}/LICENSE" "${STAGE}/META-INF/licenses/LICENSE-chdb-java.txt"
cat > "${STAGE}/META-INF/licenses/README.txt" <<EOF
This package redistributes two shared libraries:

  ${JNINAME}
      The chdb-java JNI shim, built from this repository. Apache-2.0; see
      LICENSE-chdb-java.txt.

  ${LIBNAME}
      The chDB engine, redistributed verbatim from the chdb-io/chdb-core release
      ${ENGINE_VERSION}. Apache-2.0. chDB embeds ClickHouse, which is Apache-2.0, and a
      number of third-party libraries under permissive licences. The authoritative notices
      are the ones shipped with the engine release; see
      https://github.com/chdb-io/chdb-core/releases/tag/$(prop engine.tag)
      and the ClickHouse licence inventory at
      https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-licenses/

Work plan section 4.4 tracks confirming the full redistribution notice set with the chDB
maintainers before the first Maven Central release; until that is signed off this package is
snapshot-only.
EOF

# CycloneDX 1.5, minimal but valid: enough for a consumer to see what is inside and to
# check it. The remaining task is folding in the engine's own transitive component list,
# which chdb-core publishes with its releases.
cat > "${STAGE}/META-INF/sbom/bom.json" <<EOF
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.5",
  "version": 1,
  "metadata": {
    "component": {
      "type": "library",
      "name": "${MODULE}",
      "version": "${ENGINE_VERSION}.${BINDING_REVISION}",
      "description": "chDB engine and JNI shim for ${PLATFORM}"
    }
  },
  "components": [
    {
      "type": "library",
      "name": "chdb-core",
      "version": "${ENGINE_VERSION}",
      "purl": "pkg:github/chdb-io/chdb-core@$(prop engine.tag)",
      "licenses": [{ "license": { "id": "Apache-2.0" } }],
      "hashes": [{ "alg": "SHA-256", "content": "${ENGINE_SHA}" }],
      "properties": [{ "name": "chdb:file", "value": "${LIBNAME}" }]
    },
    {
      "type": "library",
      "name": "chdb-java-jni",
      "version": "${ENGINE_VERSION}.${BINDING_REVISION}",
      "licenses": [{ "license": { "id": "Apache-2.0" } }],
      "hashes": [{ "alg": "SHA-256", "content": "${JNI_SHA}" }],
      "properties": [
        { "name": "chdb:file", "value": "${JNINAME}" },
        { "name": "chdb:commit", "value": "${GIT_COMMIT}" }
      ]
    }
  ]
}
EOF

printf '\nbuild-native: staged %s\n' "$PLATFORM"
printf '  %s\n' "${NATIVE_DIR}/${LIBNAME}"
printf '  %s\n' "${NATIVE_DIR}/${JNINAME}"
printf '  engine sha256 %s\n' "$ENGINE_SHA"
printf '  shim   sha256 %s\n' "$JNI_SHA"
printf '\nNext: mvn -pl %s package\n' "$MODULE"
